// <auto-generated />
using ECommerce.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ECommerce.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250612094714_mig_add_test_data")]
    partial class mig_add_test_data
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.6");

            modelBuilder.Entity("ECommerce.API.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.Property<int>("Stock")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Apple Telefon",
                            ImageUrl = "1.jpg",
                            IsActive = true,
                            Name = "IPhone 15 ",
                            Price = 50000m,
                            Stock = 100
                        },
                        new
                        {
                            Id = 2,
                            Description = "Apple Telefon",
                            ImageUrl = "2.jpg",
                            IsActive = true,
                            Name = "IPhone 14 ",
                            Price = 40000m,
                            Stock = 100
                        },
                        new
                        {
                            Id = 3,
                            Description = "Apple Telefon",
                            ImageUrl = "3.jpg",
                            IsActive = true,
                            Name = "IPhone 13 ",
                            Price = 30000m,
                            Stock = 100
                        },
                        new
                        {
                            Id = 4,
                            Description = "Apple Telefon",
                            ImageUrl = "4.jpg",
                            IsActive = true,
                            Name = "IPhone 12 ",
                            Price = 20000m,
                            Stock = 100
                        },
                        new
                        {
                            Id = 5,
                            Description = "Apple Telefon",
                            ImageUrl = "5.jpg",
                            IsActive = true,
                            Name = "IPhone 11 ",
                            Price = 10000m,
                            Stock = 100
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
